name:                midiot
version:             0.1.0
github:              "ejconlon/midiot"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2022 Eric Conlon"
# category:            Undefined
# synopsis:            Undefined

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/midiot#readme>

dependencies:
- base >= 4.12 && < 5
- dahdit >= 0.4.1 && < 0.5
- bytestring >= 0.11 && < 0.12
- containers >= 0.6 && < 0.7
- data-sword >= 0.2.0.3 && < 0.3
- hashable >= 1.4 && < 1.5
- newtype >= 0.2 && < 0.3
- primitive >= 0.7 && < 0.9
- text >= 1.2 && < 2.1
- time >= 1.11 && < 1.12
- vector >= 0.12 && < 0.13

default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- KindSignatures
- MultiParamTypeClasses
- MultiWayIf
- Rank2Types
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src

executables:
  midiot-exe:
    main:                Main.hs
    source-dirs:         exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - midiot

tests:
  midiot-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - midiot
    - dahdit-test
    - falsify
    - tasty
    - tasty-hunit
    - directory
    - filepath
