resolver: lts-20.20

ghc-options:
  "$everything": -haddock

packages:
- .

extra-deps:
# TODO Use Hackage version when released
# - dahdit-0.4.0
- git: git@github.com:ejconlon/dahdit.git
  commit: 068281b665f21c894d714b069ae61c89d15321a2
# TODO Use Hackage version when released
# - data-sword-0.2.0.4
- git: git@github.com:ejconlon/data-sword.git
  commit: 45406c35878d0f3efc4cf29b4f3f2182391bc27c
- primitive-0.8.0.0
- RtMidi-0.6.1.0
- falsify-0.1.1

