resolver: lts-20.22

ghc-options:
  "$everything": -haddock

packages:
- .

extra-deps:
# TODO Use Hackage version when released
# - dahdit-0.4.0
- git: git@github.com:ejconlon/dahdit.git
  commit: f02a4aad80fcd65e671453f4f83589568002a355
# TODO Use Hackage version when released
# - data-sword-0.2.0.4
- git: git@github.com:ejconlon/data-sword.git
  commit: 45406c35878d0f3efc4cf29b4f3f2182391bc27c
- primitive-0.8.0.0
- RtMidi-0.6.1.0
- falsify-0.1.1
# TODO Use Hackage version when released
- git: git@github.com:ejconlon/dahdit-test.git
  commit: 1627e917a78d72ef4391bd8bedaa55f1c4808314

